# SPDX-License-Identifier: GPL-2.0

mali-aeu-y := mali_aeu.o mali_aeu_v4l2.o mali_aeu_hw.o mali_aeu_log.o

ifneq ($(CONFIG_VIDEO_ADV_DEBUG),)
	mali-aeu-y += mali_aeu_reg_dump.o
endif

obj-$(CONFIG_MALI_AEU) += mali-aeu.o
