#
# Copyright (c) 2013 Samsung Electronics Co., Ltd.
#		http://www.samsung.com
#
# Licensed under GPLv2
#

obj-$(CONFIG_VIDEO_EXYNOS_HDMI) += s5p-hdmi.o
s5p-hdmi-y += hdmi_drv.o hdmi_edid.o hdmi_reg.o hdmiphy_conf.o hdcp_drv.o
obj-$(CONFIG_DECON_TV_FB) += decon_tv.o
decon_tv-y += decon_tv_drv.o decon_tv_reg.o
obj-$(CONFIG_VIDEO_EXYNOS_HDMI_CEC) += s5p-hdmi_cec.o
s5p-hdmi_cec-y += hdmi_cec.o hdmi_cec_ctrl.o
