#
# (C) COPYRIGHT 2012 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained
# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA.
#
#

platform_name := $(shell echo $(CONFIG_MALI_PLATFORM_THIRDPARTY_NAME))

ifeq ($(CONFIG_MALI_MIDGARD),y)
	obj-y += \
		mali_kbase_platform.o \
		gpu_notifier.o \
		gpu_control_exynos$(platform_name).o \
		gpu_control.o \
		gpu_dvfs_handler.o \
		gpu_dvfs_governor.o \
		gpu_custom_interface.o
	obj-$(CONFIG_CPU_THERMAL_IPA) += gpu_ipa.o
else ifeq ($(CONFIG_MALI_MIDGARD),m)
	SRC += \
		$(MALI_PLATFORM_THIRDPARTY_DIR)/mali_kbase_platform.c \
		$(MALI_PLATFORM_THIRDPARTY_DIR)/gpu_notifier.c \
		$(MALI_PLATFORM_THIRDPARTY_DIR)/gpu_control_exynos$(platform_name).c \
		$(MALI_PLATFORM_THIRDPARTY_DIR)/gpu_control.c \
		$(MALI_PLATFORM_THIRDPARTY_DIR)/gpu_dvfs_handler.c \
		$(MALI_PLATFORM_THIRDPARTY_DIR)/gpu_dvfs_governor.c \
		$(MALI_PLATFORM_THIRDPARTY_DIR)/gpu_custom_interface.c
	ifeq ($(CONFIG_CPU_THERMAL_IPA),y)
		SRC += $(MALI_PLATFORM_THIRDPARTY_DIR)/gpu_ipa.c
	endif
endif
