#
# (C) COPYRIGHT 2012,2014 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained
# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA.
#
#

SOC_NAME ?= 5430

ifeq ($(CONFIG_SOC_EXYNOS5250),y)
	SOC_NAME=5250
endif
ifeq ($(CONFIG_SOC_EXYNOS5412),y)
	SOC_NAME=5412
endif
ifeq ($(CONFIG_SOC_EXYNOS5420),y)
	SOC_NAME=5420
endif
ifeq ($(CONFIG_SOC_EXYNOS5422),y)
	SOC_NAME=5422
endif
ifeq ($(CONFIG_SOC_EXYNOS5430),y)
	SOC_NAME=5430
endif

ccflags-y += -DSOC_NAME=$(SOC_NAME)

SRC += \
	$(MALI_PLATFORM_THIRDPARTY_DIR)/mali_kbase_platform.c \
	$(MALI_PLATFORM_THIRDPARTY_DIR)/gpu_notifier.c \
	$(MALI_PLATFORM_THIRDPARTY_DIR)/gpu_control_exynos$(SOC_NAME).c \
	$(MALI_PLATFORM_THIRDPARTY_DIR)/gpu_control.c \
	$(MALI_PLATFORM_THIRDPARTY_DIR)/gpu_dvfs_handler.c \
	$(MALI_PLATFORM_THIRDPARTY_DIR)/gpu_dvfs_governor.c \
	$(MALI_PLATFORM_THIRDPARTY_DIR)/gpu_custom_interface.c

ifneq ($(CONFIG_CPU_THERMAL_IPA),)
	SRC += $(MALI_PLATFORM_THIRDPARTY_DIR)/gpu_ipa.c
endif
