#ifndef __SEIREN_ERROR_H
#define __SEIREN_ERROR_H

enum {
	SEIREN_RETURN_OK		= 0,

	SEIREN_ERROR_OPEN_FAIL		= -1000,
	SEIREN_ERROR_ALREADY_OPEN	= -1001,
	SEIREN_ERROR_NOT_READY		= -1002,

	SEIREN_ERROR_IBUF_OVERFLOW	= -2000,
	SEIREN_ERROR_IBUF_INFO		= -2001,

	SEIREN_ERROR_OBUF_READ		= -3000,
	SEIREN_ERROR_OBUF_INFO		= -3001,
	SEIREN_ERROR_OBUF_MMAP		= -3002,

	SEIREN_ERROR_INVALID_SETTING	= -4000,
	SEIREN_ERROR_GETINFO_FAIL	= -4001
} SEIREN_ERRORTYPE;

#endif /* __SEIREN_ERROR_H */
