#ifndef __SEIREN_IOCTL_H
#define __SEIREN_IOCTL_H

#define SEIREN_IOCTL_CH_CREATE		(0x1001)
#define SEIREN_IOCTL_CH_DESTROY		(0x1002)
#define SEIREN_IOCTL_CH_EXE		(0x1003)
#define SEIREN_IOCTL_CH_SET_PARAMS	(0x2001)
#define SEIREN_IOCTL_CH_GET_PARAMS	(0x2002)
#define SEIREN_IOCTL_CH_RESET		(0x2003)
#define SEIREN_IOCTL_CH_FLUSH		(0x2004)
#define SEIREN_IOCTL_CH_CONFIG		(0x2005)

#endif /* __SEIREN_IOCTL_H */
