# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_VEXPRESS) += foundation-v8.dtb foundation-v8-gicv3.dtb
dtb-$(CONFIG_ARCH_VEXPRESS) += juno-r0.dtb juno-r1.dtb juno-r2.dtb
dtb-$(CONFIG_ARCH_VEXPRESS) += juno-v2f-1xv7-mali-d71.dtb
dtb-$(CONFIG_ARCH_VEXPRESS) += juno-v2f-1xv7-mali-d71-smmu-v3.dtb
dtb-$(CONFIG_ARCH_VEXPRESS) += juno-v2f-1xv7-mali-d71-profpga.dtb
dtb-$(CONFIG_ARCH_VEXPRESS) += juno-v2f-1xv7-mali-d32.dtb
dtb-$(CONFIG_ARCH_VEXPRESS) += rtsm_ve-aemv8a.dtb
dtb-$(CONFIG_ARCH_VEXPRESS) += vexpress-v2f-1xv7-ca53x2.dtb

