#################################################
# Makefile for JPEG4
# 2013 (C) Samsung Electronics
#################################################

jpeg4-objs := jpeg_dev.o jpeg_core.o jpeg_regs.o jpeg_mem.o
obj-$(CONFIG_VIDEO_EXYNOS_JPEG)	+= jpeg4.o
