#
# (C) COPYRIGHT 2013-2014 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained
# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA.
#
#


ifeq ($(CONFIG_MALI_MIDGARD),m)
SRC += $(MALI_PLATFORM_THIRDPARTY_DIR)/mali_kbase_config_juno_soc.c
obj-m += $(MALI_PLATFORM_THIRDPARTY_DIR)/juno_mali_opp.o
else
obj-y += mali_kbase_config_juno_soc.o
obj-y += juno_mali_opp.o
endif
