obj-$(CONFIG_ODROID_EXYNOS5_FAN)	  += odroid_fan.o
obj-$(CONFIG_ODROID_EXYNOS5_SP)       += ina231-sensor.o
ina231-sensor-y := ina231-misc.o ina231-sysfs.o ina231-i2c.o
obj-$(CONFIG_ODROID_EXYNOS5_IOBOARD)  += ioboard-bh1780.o ioboard-bmp180.o ioboard-keyled.o
obj-$(CONFIG_ODROID_EXYNOS5_IOBOARD)  += ioboard-spi-flash.o
ioboard-spi-flash-y := ioboard-spi.o ioboard-spi-misc.o
