#
# (C) COPYRIGHT 2012 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained
# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA.
#
#

MALI_CUSTOMER_RELEASE = 1

platform_name := $(shell echo $(CONFIG_MALI_PLATFORM_THIRDPARTY_NAME))

ccflags-$(CONFIG_MALI_T6XX) += -I$(src)/../../t6xx/kbase/src/common

obj-y += mali_kbase_platform.o
obj-y += gpu_notifier.o
obj-y += gpu_control_exynos$(platform_name).o
obj-y += gpu_control.o
obj-y += gpu_dvfs_handler.o
obj-y += gpu_dvfs_governor.o
obj-y += gpu_custom_interface.o
obj-$(CONFIG_CPU_THERMAL_IPA) += gpu_ipa.o
