#################################################
# Makefile for HX JPEG
# 2013 (C) Samsung Electronics
#################################################

jpeg_hx-objs := jpeg_hx_dev.o jpeg_hx_dec.o jpeg_hx_enc.o jpeg_hx_regs.o jpeg_hx_mem.o
obj-$(CONFIG_VIDEO_EXYNOS_HX_JPEG)	+= jpeg_hx.o
