#
# Samsung Clock specific Makefile
#

obj-$(CONFIG_COMMON_CLK)		+= clk.o clk-pll.o
obj-$(CONFIG_ARCH_EXYNOS4)		+= clk-exynos4.o
obj-$(CONFIG_SOC_EXYNOS5250)		+= clk-exynos5250.o
obj-$(CONFIG_SOC_EXYNOS5430_REV_0)	+= clk-exynos5430_evt0.o init-exynos5430_evt0.o
obj-$(CONFIG_SOC_EXYNOS5430_REV_1)	+= clk-exynos5430.o init-exynos5430.o
obj-$(CONFIG_SOC_EXYNOS5422)		+= clk-exynos5422.o init-exynos5422.o
obj-$(CONFIG_SOC_EXYNOS5440)		+= clk-exynos5440.o
obj-$(CONFIG_ARCH_EXYNOS)		+= clk-exynos-audss.o
obj-$(CONFIG_PWM_SAMSUNG)		+= clk-exynos-pwm.o
