# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_DRM_KOMEDA) += komeda/

obj-$(CONFIG_ASSERTIVE_DISPLAY) += ad/

obj-$(CONFIG_ASSERTIVE_DISPLAY_TEST_MODULE) += ad/test_module/

obj-$(CONFIG_COPROC_SERVER) += co-processor/
